config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails do
    resources :doses, only: [:new, :create] # "restaurants/:restaurant_id/reviews/new"
  end

  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]
  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end


  def edit
  end


   def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
  @cocktail.destroy
  redirect_to cocktails_url
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
    end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<div class="vontainer">
<%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name %>
    <%= f.button :submit %>
    <%= f.input :photo, as: :file %>
<% end %>
</div>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1597683684712-9e4ecc69132a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80);">
    <div class="container">
      <h1>Welcome in <strong>Brasil</strong></h1>
    </div>
  </div>

<div class="row row-cols-2 row-cols-md-2">
    <% @cocktails.each do |cocktail|  %>
      <div class="col-6 col-md-3">
        <td><%= cocktail.name %></td>
        <%= link_to 'voir', cocktail %>
        <%#= link_to 'edit', edit_cocktail_path(@cocktail) %>
        <%= link_to 'destroy', cocktail, method: :delete, class:"btn btn-danger"  %>
        <div class="card-product flex d-flex" style="width: 18rem;">
          <div class="card-body">
            <% if cocktail.photo.attachment %>
              <%= cl_image_tag cocktail.photo.key %>
            <% else %>
              <h1>ok</h1>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
 </div>
    <div>
         <%= link_to 'new', new_cocktail_path, class:"btn btn-primary" %>
    </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">

<%= render 'form', cocktail: @cocktail %>
<%= link_to 'Back', cocktails_path %>

</div>

app/views/cocktails/show.html.erb
<div class="container">

<%= @cocktail.name %>
<% @cocktail.doses.each do |dose|  %>
<%= dose.ingredient.name %>
<p>...</p>
 <%= dose.description %>
<%= link_to "destroy", dose, method: :delete   %>
<% end %>
<%= link_to "ajouter une dose", new_cocktail_dose_path(@cocktail)  %>
<%= link_to "back", cocktails_path  %>
</div>

app/views/doses/new.html.erb
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.submit "Submit dose", class: 'btn btn-primary' %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>
  </body>
</html>